### ISSUE TITLE
Unable to delete bot

### ISSUE THREAD

**Issue by CircuitSacul** [discordlist-gg/beta-issues#169]
### Description
@ChillFish8 opened an issue for this just cause, close it if you want.

https://circuit.is-from.space/Screen_Recording_2022-05-14_at_6.45.32_PM.mov

**Comment by ChillFish8** [comment]
This should be fixed now / server error is resolved.

**Comment by CircuitSacul** [comment]
@ChillFish8 still get the same error, even though the bot still deletes.

**Comment by ChillFish8** [comment]
Are you able to try again now? This should be resolved.

**Comment by CircuitSacul** [comment]
Resolved
