### ISSUE TITLE
[ui] background is too narrow on bot pack dropdown menu

### ISSUE THREAD

**Issue by lewisfm** [discordlist-gg/beta-issues#311]
### Page

https://discordlist.gg/pack/:id

### Description

![Screen Shot 2022-10-23 at 8 06 20 PM](https://user-images.githubusercontent.com/75394401/197440836-aefedf06-2b0c-464d-ac93-d44ba33f086a.png)

### What browsers are you seeing the problem on?

Safari

### Notify on issue updates

- [X] Yes

### Discord username

doinkythederp#6523

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.

**This fix will not be live until early next week.**

_Thank you for contributing during beta!_

**Comment by lewisfm** [comment]
@audn I'm still seeing this problem on the website.

![Screenshot 2022-11-13 at 11 44 20 AM](https://user-images.githubusercontent.com/75394401/201541076-33e117ae-35c9-46e6-b679-3b540f2b42b4.png)
On hover:
![Screenshot 2022-11-13 at 11 45 24 AM](https://user-images.githubusercontent.com/75394401/201541110-0f46efbc-143b-4582-b960-6c797d376608.png)

Removing `sm:absolute` from the highlighted element seems to fix it for me:
![Screenshot 2022-11-13 at 11 51 48 AM](https://user-images.githubusercontent.com/75394401/201541428-40e4220e-28a1-4c62-8dd4-81183754cc9a.png)
![Screenshot 2022-11-13 at 11 50 17 AM](https://user-images.githubusercontent.com/75394401/201541431-74f4575a-e7e5-48cb-b3c4-75be252b7622.png)
